//
// Created by kicie on 07/11/2025.
//

#ifndef UNTITLEDTEXTGAME_CHOOSEPLAYERGENDER_H
#define UNTITLEDTEXTGAME_CHOOSEPLAYERGENDER_H
int choosePlayerGender();
#endif //UNTITLEDTEXTGAME_CHOOSEPLAYERGENDER_H