//
// Created by kicie on 07/11/2025.
//

#ifndef UNTITLEDTEXTGAME_CHOOSEPLAYERCLASS_H
#define UNTITLEDTEXTGAME_CHOOSEPLAYERCLASS_H
int choosePlayerClass();

#endif //UNTITLEDTEXTGAME_CHOOSEPLAYERCLASS_H